name: Build & Run

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Setup Node.js
        uses: actions/setup-node@v1.1.0
      - name: Install yarn
        run: curl -o- -L https://yarnpkg.com/install.sh | bash
      - name: Install VueCLI
        run: |
          yarn global add @vue/cli
          export PATH="$(yarn global bin):$PATH"
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install yarn dependencies and Test JS
        run: |
          cd frontend
          yarn install
          yarn run build
          yarn run lint
